# Generated by Django 2.1 on 2019-12-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='EndYear',
            field=models.DateField(default='2019-09-09'),
        ),
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='startYear',
            field=models.DateField(default='2019-09-09'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='post',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='profile',
            field=models.ImageField(upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_title',
            field=models.CharField(max_length=20),
        ),
    ]
