# Generated by Django 2.1 on 2019-12-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0002_auto_20191209_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='nationality',
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='website',
            field=models.URLField(blank=True, help_text="Leave Blank if you don't have one", null=True),
        ),
    ]
