# Generated by Django 2.1 on 2020-01-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0003_auto_20191209_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='description',
            field=models.TextField(blank=True, help_text='About Yourself', null=True),
        ),
    ]
