# Generated by Django 2.1 on 2020-01-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0004_personaldetails_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldetails',
            old_name='description',
            new_name='objective',
        ),
    ]
