# Generated by Django 2.1 on 2020-02-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0006_auto_20200118_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='objective',
            field=models.TextField(help_text='About Yourself'),
        ),
    ]
