# Generated by Django 2.1 on 2020-02-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0008_personaldetails_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='first_login',
            field=models.IntegerField(default=1),
        ),
    ]
