# Generated by Django 2.1 on 2020-02-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0009_auto_20200207_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='first_login',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='AreYouRobot',
            field=models.BooleanField(default=True),
        ),
    ]
