# Generated by Django 2.1 on 2020-02-07 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0010_auto_20200207_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='AreYouRobot',
        ),
    ]
