# Generated by Django 3.1.5 on 2021-02-04 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0011_remove_personaldetails_areyourobot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='full_name',
        ),
    ]
