# Generated by Django 3.1.5 on 2021-02-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0012_remove_personaldetails_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='full_name',
            field=models.CharField(default='bernhardt guys', max_length=100),
            preserve_default=False,
        ),
    ]
